on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    
    jobs:
      build_and_test:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout projecct code
            uses: actions/checkout@v4
    
          - name: Set up on JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'
              cache: 'maven'
    
          - name: Run Build and Tests
            run: mvn -B package --file pom.xml